# Set how many application instances to run.
replicaCount: 1

image:
  repository: get-the-docs/docs-generator-api
  tag: sha-8ab657b
  pullPolicy: IfNotPresent

imageCredentials: [{ name: gh-getthedocs}]

# Set service type: LoadBalancer, ClusterIP, NodePort
service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Set to false to disable Prometheus support.
monitoring: true

# Set configuration properties.
config:

  application:
    spring:
      config:
        activate:
          on-profile: prod

      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://localhost/realms/getthedocs

    springdoc:
      swagger-ui:
        oauth2-redirect-url: http://localhost/auth/realms/getthedocs

  documentengine:
    # -------------------------
    # Document-engine properties
    # -------------------------

    # Document structure anf value object logging category
    # -----------------------------
    #   If specified, the document structure and the actual value set can be logged with a separate logger.
    #   To do so, enable a log category specified by this setting.
    #   The logging is bound to DEBUG log level and is logged by default through the TemplateService's logger.
    # common.log.value-logcategory= org.getthedocs.templateutils.valuelog

    repository:

      # Document structure repository provider
      documentstructure:
        provider:
          basedir: /repositories/source/documentstructures
          storageclass: docs-documentstructures-sc
          requests:
            storage: 100Mi
        builder: org.getthedocs.documentengine.template.core.provider.documentstructure.builder.yaml.YmlDocStructureBuilder

      # Template repository provider class
      templates:
        provider:
          basedir: /repositories/source/templates
          storageclass: docs-templates-sc
          requests:
            storage: 100Mi

      # InputTemplate processors
      processors:
        docx: org.getthedocs.documentengine.template.core.processor.input.docx.DocxStamperInputTemplateProcessor
        xlsx: org.getthedocs.documentengine.template.core.processor.input.xlsx.JxlsInputTemplateProcessor

      # Result repository provider class
      result:
        provider:
          basedir: /repositories/target/generated-documents
          storageclass: docs-results-sc
          requests:
            storage: 1Gi

    # Converters/PDF - Font library
    # -----------------------------
    #   For non built-in fonts (other then COURIER, HELVETICA, TIMES_ROMAN) the fonts used by the source documents
    #   have to be provided.
    #   The fonts will be embedded for the correct appearance into the result document.
    #   Usage:
    #     the fonts have to be specified as shown in the example below and
    #     placed in a directory accessible for the TemplateService's class loader (e.g. have to be on the classpath).

    # Font base directory
    converter:
      pdf:
        fontLibrary:
          basedir: /fonts
          storageclass: docs-fonts-sc
          requests:
            storage: 100Mi