app:
  api:
    project-name: "@project.name@"
    version: "@project.version@"
    base-path: "/v1"
    swagger-resource-path: "/v1/templates"
  http: 
    auth-token-name: "x-api-key"
    auth-token: "51af3e7e-f3dd-4751-8c0a-42a40450b694"


springdoc:
  swagger-ui:
    syntaxHighlight:
      activated: false
      theme: "monokai"
    path: "/v1/templates/swagger-ui"
    disable-swagger-default-url: true
  api-docs:
    path: "/v1/templates/swagger-ui/v3/api-docs"

spring:
  profiles:
    active: prod

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
#  security:
#    basic:
#      enabled: false

logging:
  level:
    io:
      swagger:
        models:
        parameters:
          AbstractSerializableParameter: "error"

server:
  port: "${SERVER_PORT:8081}"

---

spring:
  config:
    activate:
      on-profile: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_RESOURCE_SERVER:http://localhost/realms/getthedocs}
#          jwk-set-uri: ${OAUTH_RESOURCE_SERVER:http://localhost/realms/getthedocs/protocol/openid-connect/certs}

springdoc:
  swagger-ui:
    oauth2-redirect-url: ${OAUTH_RESOURCE_SERVER:http://localhost/auth/realms/getthedocs}