apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spring-boot.name" . }}
    helm.sh/chart: {{ include "spring-boot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Values.service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spring-boot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spring-boot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.monitoring }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
      {{- end }}
    spec:
      {{- with .Values.imageCredentials }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9001
            initialDelaySeconds: 20
          volumeMounts:
          - mountPath: /repositories/source/documentstructures
            name: documentstructures
          - mountPath: /repositories/source/templates
            name: templates
          - mountPath: /fonts
            name: fonts
          - mountPath: /repositories/target/generated-documents
            name: generated-documents
      volumes:
      - name: documentstructures
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-documentstructures
      - name: templates
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-templates
      - name: fonts
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-fonts
      - name: generated-documents
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-generateddocuments

