language: java
install: true

sudo: false
jdk:
  - openjdk11

stages:
  - name: build

jobs:
  include:

    - stage: build

      before_cache:
        - rm -fr $HOME/.m2/repository/net/videki/

      cache:
        yarn: true
        directories:
          - $HOME/.m2

      script:
        - set -e
        - /bin/bash ./bin/utils/detect_merge_conflict.sh
        - /bin/bash ./bin/utils/detect_tab_in_java_class.sh
        - mvn --no-snapshot-updates --quiet --batch-mode --show-version clean install # -Dorg.slf4j.simpleLogger.defaultLogLevel=error
