/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.videki.templateutils.service.controller;

import net.videki.templateutils.service.model.BaseApiResponse;
import net.videki.templateutils.service.model.TemplateJobApiResponse;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-02-19T13:46:54.021161300+01:00[Europe/Prague]")

@Validated
@Api(value = "template", description = "the template API")
public interface TemplateApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /template/{id} : Posts a template generation with the given data
     *
     * @param id template id in the template repository. Important: The directory separator characters should be replaced to &#39;|&#39; (required)
     * @param body data provided for generation (required)
     * @return Default (status code 202)
     *         or Invalid DTO (status code 400)
     *         or Bad credentials (status code 401)
     *         or Forbidden (status code 403)
     *         or Template not found (status code 404)
     *         or Too many requests (status code 429)
     *         or Default (status code 200)
     */
    @ApiOperation(value = "Posts a template generation with the given data", nickname = "postTemplateGenerationJob", notes = "", response = TemplateJobApiResponse.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Default", response = TemplateJobApiResponse.class),
        @ApiResponse(code = 400, message = "Invalid DTO", response = BaseApiResponse.class),
        @ApiResponse(code = 401, message = "Bad credentials", response = BaseApiResponse.class),
        @ApiResponse(code = 403, message = "Forbidden", response = BaseApiResponse.class),
        @ApiResponse(code = 404, message = "Template not found", response = BaseApiResponse.class),
        @ApiResponse(code = 429, message = "Too many requests", response = BaseApiResponse.class),
        @ApiResponse(code = 200, message = "Default", response = TemplateJobApiResponse.class) })
    @RequestMapping(value = "/template/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<TemplateJobApiResponse> postTemplateGenerationJob(@Size(min=1,max=4000) @ApiParam(value = "template id in the template repository. Important: The directory separator characters should be replaced to '|'",required=true) @PathVariable("id") String id,@ApiParam(value = "data provided for generation" ,required=true )  @Valid @RequestBody Object body) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\", \"transactionId\" : \"transactionId\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
