app:
  api:
    base-path: "/api/v1"
  http: 
    auth-token-name: "x-api-key"
    auth-token: "51af3e7e-f3dd-4751-8c0a-42a40450b694"

springfox: 
  documentation:
    swagger:
      v2:
        path: "/api-docs"

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
  security:
    basic:
      enabled: false
    
logging:
  level:
    io:
      swagger:
        models:
        parameters:
          AbstractSerializableParameter: "error"

server:
  port: "${SERVER_PORT:8081}"
