# contract_v02.yml
---
documentStructureId: "109a562d-8290-407d-98e1-e5e31c9808b7"
elements:
  - templateElementId:
      id: "cover"
    templateNames:
      hu: "integrationtests/covers/cover_v03.docx"
    defaultLocale: "hu_HU"
    count: 1
  - templateElementId:
      id: "contract"
    templateNames:
      en: "integrationtests/contracts/contract_v09_en.docx"
      hu: "integrationtests/contracts/contract_v09_hu.docx"
    defaultLocale: "hu_HU"
    count: 1
  - templateElementId:
      id: "terms"
    templateNames:
      hu: "integrationtests/terms/terms_v02.docx"
    defaultLocale: "hu_HU"
    count: 1
  - templateElementId:
      id: "conditions"
    templateNames:
      hu: "integrationtests/conditions/vintage/conditions_eco_v11.xlsx"
    defaultLocale: "hu"
    count: 1
resultMode: "SINGLE_OUTPUT"
outputFormat: "PDF"
copies: 3