name: Build

on:
  push:
    paths:
      - 'template-utils-*/**'
      - 'pom.xml'
jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/net/videki/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true

#      - name: Archive production artifacts
#        if: ${{ success() }}
#        uses: actions/upload-artifact@v1
#        with:
#          name: template-utils-core
#          path: /home/runner/work/template-utils/template-utils/template-utils-core/target/template-utils-core-1.0.1.jar
#          path: ${{ github.workspace }}/**/target/template-utils*.jar
