name: Build

on:
  push:
    branches: [ "main", release/*, story/*, task/* ]
    paths:
      - 'docs-*/**'
      - 'pom.xml'
      - '.github/workflows/**'
  pull_request:
    #    branches: [ "main" ]
    types: [opened, synchronize, reopened]
    paths:
      - 'docs-*/**'
      - 'pom.xml'
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven build
        run: mvn -B package --file pom.xml -DskipTests=true

  test_job:
    name: Run tests
    needs: build_job
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven verify
        run: mvn -B verify --file pom.xml -Dspring.profiles.active=local

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/target/surefire-reports/TEST-*.xml
            **/target/failsafe-reports/TEST-*.xml


  test_report_job:
    name: Create test reports
    needs:
    - build_job
    - test_job

    runs-on: ubuntu-latest
    steps:
      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: dorny/test-reporter@v2
        with:
          artifact: test-results            # artifact name
          name: Tests                       # Name of the check run which will be created
          path: '**/*.xml'                  # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Maven site
        run: mvn -B verify site --file pom.xml -Dspring.profiles.active=local

      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: '**/target/site/**'

  coverage_job:
    name: Coverage check
    needs:
      - test_job
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      #      - name: Rebuild local Maven repository from cache
      #        uses: actions/cache@v3
      #        with:
      #          path: |
      #            ~/.m2/repository
      #            !~/.m2/repository/net/videki/**
      #          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #          restore-keys: |
      #            ${{ runner.os }}-maven-

      - name: Maven verify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn -B verify --file pom.xml -Dspring.profiles.active=local -Pcoverage

      - name: Run Clover coverage and upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          name: document-engine
        #    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #    files: ./coverage1.xml,./coverage2.xml # optional
        #    flags: unittests # optional
        #    fail_ci_if_error: true # optional (default = false)
        #    verbose: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
