name: Build

env:
  CODECOV_TOKEN: 39e3c96b-a8b8-4e07-b52c-13880a73db37

on: [push]

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/net/videki/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true

      - name: Archive production artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v1
        with:
          name: template-utils-core-$GITHUB_SHA
          path: /home/runner/work/template-utils/template-utils/template-utils-core/target/template-utils-core-1.0.1.jar
#          path: ${{ github.workspace }}/**/target/template-utils*.jar
