name: Coverage

env:
  CODECOV_TOKEN: 39e3c96b-a8b8-4e07-b52c-13880a73db37

on:
  push:
    paths:
      - 'template-utils-*/**'
      - 'pom.xml'

jobs:
  coverage_job:
    name: Run coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/net/videki/**
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B verify --file pom.xml -Pcoverage

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
#    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#    files: ./coverage1.xml,./coverage2.xml # optional
#    flags: unittests # optional
#    fail_ci_if_error: true # optional (default = false)
#    verbose: true # optional (default = false)

    - name: Codecov upload
      run: bash <(curl -s https://codecov.io/bash)

#    - name: Archive code coverage results
#      if: ${{ success() }}
#      uses: actions/upload-artifact@v1
#      with:
 #       name: code-coverage-report
 #       path: ${{ github.workspace }}/**/target/site/jacoco/*
