name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B cobertura:cobertura --file pom.xml

    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        name: template-utils
        token: 39e3c96b-a8b8-4e07-b52c-13880a73db37
        # Path to coverage file to upload
#        file: # optional
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
#        flags: # optional
        # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
#        env_vars: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
#        fail_ci_if_error: # optional

    - name: Codecov upload
      run: bash <(curl -s https://codecov.io/bash)

