name: Release

env:
  MAVEN_OPTS: " -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN "
  MAVEN_CLI_SETTINGS: " -s .github/workflows/settings.xml "
  MAVEN_CLI_OPTS: " --show-version --batch-mode --no-transfer-progress "

on:
  release:
    types: [ published ]

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests $MAVEN_OPTS $MAVEN_CLI_OPTS

  test_job:
    name: Test
    runs-on: ubuntu-latest
    needs: build_job

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test build
        run: mvn clean verify $MAVEN_OPTS $MAVEN_CLI_OPTS

  release_job:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build_job
      - test_job
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
          gpg-private-key: ${{ secrets.MAVEN_RELEASE_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_RELEASE_GPG_PASSPHRASE }}

      - name: Rebuild local Maven repository from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/getthedocs/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Release version: $VERSION"
          mvn versions:set -DnewVersion=${VERSION#v}


      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests $MAVEN_CLI_OPTS $MAVEN_CLI_SETTINGS
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PRIVATE_KEY_ID: ${{ secrets.MAVEN_RELEASE_GPG_PRIVATE_KEY_ID }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_RELEASE_GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
